package go-chart
import (
github_com_wcharczuk_go_chart "github.com/wcharczuk/go-chart"
)
func Load(Interfaces ...interface{}) {
	if len(Interfaces) > 5 {
		if i, ok := Interfaces[0].(map[string]map[string]interface{}) {
			 DefaultGojaInterfaces: = i
			 if i, ok := Interfaces[1].(*goja.Runtime) {
				vm := i
				if i, ok := Interfaces[2].(*quickjs.Context) {
					ctx := i	
					if i, ok := Interfaces[3].(func(*quickjs.Context, interface{}) (quickjs.Value, string)) {
						ConvertInterfaceToQuickJS := i
						if i, ok := Interfaces[4].(func(interface{}, ...interface{}) interface{}) {
							ExecuteFunction := i
if _, ok := DefaultGojaInterfaces["gochart"]; !ok {
   DefaultGojaInterfaces["gochart"] = map[string]interface{}{}
}
DefaultGojaInterfaces["gochart"]["DefaultChartHeight"] = github_com_wcharczuk_go_chart.DefaultChartHeight
DefaultGojaInterfaces["gochart"]["DefaultChartWidth"] = github_com_wcharczuk_go_chart.DefaultChartWidth
DefaultGojaInterfaces["gochart"]["DefaultStrokeWidth"] = github_com_wcharczuk_go_chart.DefaultStrokeWidth
DefaultGojaInterfaces["gochart"]["DefaultDotWidth"] = github_com_wcharczuk_go_chart.DefaultDotWidth
DefaultGojaInterfaces["gochart"]["DefaultSeriesLineWidth"] = github_com_wcharczuk_go_chart.DefaultSeriesLineWidth
DefaultGojaInterfaces["gochart"]["DefaultAxisLineWidth"] = github_com_wcharczuk_go_chart.DefaultAxisLineWidth
DefaultGojaInterfaces["gochart"]["DefaultDPI"] = github_com_wcharczuk_go_chart.DefaultDPI
DefaultGojaInterfaces["gochart"]["DefaultMinimumFontSize"] = github_com_wcharczuk_go_chart.DefaultMinimumFontSize
DefaultGojaInterfaces["gochart"]["DefaultFontSize"] = github_com_wcharczuk_go_chart.DefaultFontSize
DefaultGojaInterfaces["gochart"]["DefaultTitleFontSize"] = github_com_wcharczuk_go_chart.DefaultTitleFontSize
DefaultGojaInterfaces["gochart"]["DefaultAnnotationDeltaWidth"] = github_com_wcharczuk_go_chart.DefaultAnnotationDeltaWidth
DefaultGojaInterfaces["gochart"]["DefaultAnnotationFontSize"] = github_com_wcharczuk_go_chart.DefaultAnnotationFontSize
DefaultGojaInterfaces["gochart"]["DefaultAxisFontSize"] = github_com_wcharczuk_go_chart.DefaultAxisFontSize
DefaultGojaInterfaces["gochart"]["DefaultTitleTop"] = github_com_wcharczuk_go_chart.DefaultTitleTop
DefaultGojaInterfaces["gochart"]["DefaultBackgroundStrokeWidth"] = github_com_wcharczuk_go_chart.DefaultBackgroundStrokeWidth
DefaultGojaInterfaces["gochart"]["DefaultCanvasStrokeWidth"] = github_com_wcharczuk_go_chart.DefaultCanvasStrokeWidth
DefaultGojaInterfaces["gochart"]["DefaultLineSpacing"] = github_com_wcharczuk_go_chart.DefaultLineSpacing
DefaultGojaInterfaces["gochart"]["DefaultYAxisMargin"] = github_com_wcharczuk_go_chart.DefaultYAxisMargin
DefaultGojaInterfaces["gochart"]["DefaultXAxisMargin"] = github_com_wcharczuk_go_chart.DefaultXAxisMargin
DefaultGojaInterfaces["gochart"]["DefaultVerticalTickHeight"] = github_com_wcharczuk_go_chart.DefaultVerticalTickHeight
DefaultGojaInterfaces["gochart"]["DefaultHorizontalTickWidth"] = github_com_wcharczuk_go_chart.DefaultHorizontalTickWidth
DefaultGojaInterfaces["gochart"]["DefaultTickCount"] = github_com_wcharczuk_go_chart.DefaultTickCount
DefaultGojaInterfaces["gochart"]["DefaultTickCountSanityCheck"] = github_com_wcharczuk_go_chart.DefaultTickCountSanityCheck
DefaultGojaInterfaces["gochart"]["DefaultMinimumTickHorizontalSpacing"] = github_com_wcharczuk_go_chart.DefaultMinimumTickHorizontalSpacing
DefaultGojaInterfaces["gochart"]["DefaultMinimumTickVerticalSpacing"] = github_com_wcharczuk_go_chart.DefaultMinimumTickVerticalSpacing
DefaultGojaInterfaces["gochart"]["DefaultDateFormat"] = github_com_wcharczuk_go_chart.DefaultDateFormat
DefaultGojaInterfaces["gochart"]["DefaultDateHourFormat"] = github_com_wcharczuk_go_chart.DefaultDateHourFormat
DefaultGojaInterfaces["gochart"]["DefaultDateMinuteFormat"] = github_com_wcharczuk_go_chart.DefaultDateMinuteFormat
DefaultGojaInterfaces["gochart"]["DefaultFloatFormat"] = github_com_wcharczuk_go_chart.DefaultFloatFormat
DefaultGojaInterfaces["gochart"]["DefaultPercentValueFormat"] = github_com_wcharczuk_go_chart.DefaultPercentValueFormat
DefaultGojaInterfaces["gochart"]["DefaultBarSpacing"] = github_com_wcharczuk_go_chart.DefaultBarSpacing
DefaultGojaInterfaces["gochart"]["DefaultBarWidth"] = github_com_wcharczuk_go_chart.DefaultBarWidth
DefaultGojaInterfaces["gochart"]["ContentTypePNG"] = github_com_wcharczuk_go_chart.ContentTypePNG
DefaultGojaInterfaces["gochart"]["ContentTypeSVG"] = github_com_wcharczuk_go_chart.ContentTypeSVG
DefaultGojaInterfaces["gochart"]["DefaultMACDPeriodPrimary"] = github_com_wcharczuk_go_chart.DefaultMACDPeriodPrimary
DefaultGojaInterfaces["gochart"]["DefaultMACDPeriodSecondary"] = github_com_wcharczuk_go_chart.DefaultMACDPeriodSecondary
DefaultGojaInterfaces["gochart"]["DefaultMACDSignalPeriod"] = github_com_wcharczuk_go_chart.DefaultMACDSignalPeriod
DefaultGojaInterfaces["gochart"]["DefaultEMAPeriod"] = github_com_wcharczuk_go_chart.DefaultEMAPeriod
DefaultGojaInterfaces["gochart"]["DefaultSimpleMovingAveragePeriod"] = github_com_wcharczuk_go_chart.DefaultSimpleMovingAveragePeriod
DefaultGojaInterfaces["gochart"]["Disabled"] = github_com_wcharczuk_go_chart.Disabled
DefaultGojaInterfaces["gochart"]["AlternateColorPalette"] = github_com_wcharczuk_go_chart.AlternateColorPalette
DefaultGojaInterfaces["gochart"]["DefaultColorPalette"] = github_com_wcharczuk_go_chart.DefaultColorPalette
DefaultGojaInterfaces["gochart"]["FloatValueFormatter"] = github_com_wcharczuk_go_chart.FloatValueFormatter
DefaultGojaInterfaces["gochart"]["FloatValueFormatterWithFormat"] = github_com_wcharczuk_go_chart.FloatValueFormatterWithFormat
DefaultGojaInterfaces["gochart"]["GetAlternateColor"] = github_com_wcharczuk_go_chart.GetAlternateColor
DefaultGojaInterfaces["gochart"]["GetDefaultColor"] = github_com_wcharczuk_go_chart.GetDefaultColor
DefaultGojaInterfaces["gochart"]["GetDefaultFont"] = github_com_wcharczuk_go_chart.GetDefaultFont
DefaultGojaInterfaces["gochart"]["Jet"] = github_com_wcharczuk_go_chart.Jet
DefaultGojaInterfaces["gochart"]["PercentValueFormatter"] = github_com_wcharczuk_go_chart.PercentValueFormatter
DefaultGojaInterfaces["gochart"]["TimeDateValueFormatter"] = github_com_wcharczuk_go_chart.TimeDateValueFormatter
DefaultGojaInterfaces["gochart"]["TimeHourValueFormatter"] = github_com_wcharczuk_go_chart.TimeHourValueFormatter
DefaultGojaInterfaces["gochart"]["TimeMinuteValueFormatter"] = github_com_wcharczuk_go_chart.TimeMinuteValueFormatter
DefaultGojaInterfaces["gochart"]["TimeValueFormatter"] = github_com_wcharczuk_go_chart.TimeValueFormatter
DefaultGojaInterfaces["gochart"]["Viridis"] = github_com_wcharczuk_go_chart.Viridis
DefaultGojaInterfaces["gochart"]["AnnotationSeries"] = github_com_wcharczuk_go_chart.AnnotationSeries{}
DefaultGojaInterfaces["gochart"]["LastValueAnnotation"] = github_com_wcharczuk_go_chart.LastValueAnnotation
DefaultGojaInterfaces["gochart"]["BarChart"] = github_com_wcharczuk_go_chart.BarChart{}
DefaultGojaInterfaces["gochart"]["BollingerBandsSeries"] = github_com_wcharczuk_go_chart.BollingerBandsSeries{}
DefaultGojaInterfaces["gochart"]["Box"] = github_com_wcharczuk_go_chart.Box{}
DefaultGojaInterfaces["gochart"]["NewBox"] = github_com_wcharczuk_go_chart.NewBox
DefaultGojaInterfaces["gochart"]["BoxCorners"] = github_com_wcharczuk_go_chart.BoxCorners{}
DefaultGojaInterfaces["gochart"]["Chart"] = github_com_wcharczuk_go_chart.Chart{}
DefaultGojaInterfaces["gochart"]["ContinuousRange"] = github_com_wcharczuk_go_chart.ContinuousRange{}
DefaultGojaInterfaces["gochart"]["ContinuousSeries"] = github_com_wcharczuk_go_chart.ContinuousSeries{}
DefaultGojaInterfaces["gochart"]["EMASeries"] = github_com_wcharczuk_go_chart.EMASeries{}
DefaultGojaInterfaces["gochart"]["GridLine"] = github_com_wcharczuk_go_chart.GridLine{}
DefaultGojaInterfaces["gochart"]["GenerateGridLines"] = github_com_wcharczuk_go_chart.GenerateGridLines
DefaultGojaInterfaces["gochart"]["HistogramSeries"] = github_com_wcharczuk_go_chart.HistogramSeries{}
DefaultGojaInterfaces["gochart"]["ImageWriter"] = github_com_wcharczuk_go_chart.ImageWriter{}
DefaultGojaInterfaces["gochart"]["LinearRegressionSeries"] = github_com_wcharczuk_go_chart.LinearRegressionSeries{}
DefaultGojaInterfaces["gochart"]["MACDLineSeries"] = github_com_wcharczuk_go_chart.MACDLineSeries{}
DefaultGojaInterfaces["gochart"]["MACDSeries"] = github_com_wcharczuk_go_chart.MACDSeries{}
DefaultGojaInterfaces["gochart"]["MACDSignalSeries"] = github_com_wcharczuk_go_chart.MACDSignalSeries{}
DefaultGojaInterfaces["gochart"]["MarketHoursRange"] = github_com_wcharczuk_go_chart.MarketHoursRange{}
DefaultGojaInterfaces["gochart"]["MaxSeries"] = github_com_wcharczuk_go_chart.MaxSeries{}
DefaultGojaInterfaces["gochart"]["MinSeries"] = github_com_wcharczuk_go_chart.MinSeries{}
DefaultGojaInterfaces["gochart"]["PieChart"] = github_com_wcharczuk_go_chart.PieChart{}
DefaultGojaInterfaces["gochart"]["Point"] = github_com_wcharczuk_go_chart.Point{}
DefaultGojaInterfaces["gochart"]["PolynomialRegressionSeries"] = github_com_wcharczuk_go_chart.PolynomialRegressionSeries{}
DefaultGojaInterfaces["gochart"]["Legend"] = github_com_wcharczuk_go_chart.Legend
DefaultGojaInterfaces["gochart"]["LegendLeft"] = github_com_wcharczuk_go_chart.LegendLeft
DefaultGojaInterfaces["gochart"]["LegendThin"] = github_com_wcharczuk_go_chart.LegendThin
DefaultGojaInterfaces["gochart"]["PNG"] = github_com_wcharczuk_go_chart.PNG
DefaultGojaInterfaces["gochart"]["SVG"] = github_com_wcharczuk_go_chart.SVG
DefaultGojaInterfaces["gochart"]["SMASeries"] = github_com_wcharczuk_go_chart.SMASeries{}
DefaultGojaInterfaces["gochart"]["StackedBar"] = github_com_wcharczuk_go_chart.StackedBar{}
DefaultGojaInterfaces["gochart"]["StackedBarChart"] = github_com_wcharczuk_go_chart.StackedBarChart{}
DefaultGojaInterfaces["gochart"]["Style"] = github_com_wcharczuk_go_chart.Style{}
DefaultGojaInterfaces["gochart"]["StyleShow"] = github_com_wcharczuk_go_chart.StyleShow
DefaultGojaInterfaces["gochart"]["StyleTextDefaults"] = github_com_wcharczuk_go_chart.StyleTextDefaults
DefaultGojaInterfaces["gochart"]["TextHorizontalAlignUnset"] = github_com_wcharczuk_go_chart.TextHorizontalAlignUnset
DefaultGojaInterfaces["gochart"]["TextHorizontalAlignLeft"] = github_com_wcharczuk_go_chart.TextHorizontalAlignLeft
DefaultGojaInterfaces["gochart"]["TextHorizontalAlignCenter"] = github_com_wcharczuk_go_chart.TextHorizontalAlignCenter
DefaultGojaInterfaces["gochart"]["TextHorizontalAlignRight"] = github_com_wcharczuk_go_chart.TextHorizontalAlignRight
DefaultGojaInterfaces["gochart"]["TextStyle"] = github_com_wcharczuk_go_chart.TextStyle{}
DefaultGojaInterfaces["gochart"]["TextVerticalAlignUnset"] = github_com_wcharczuk_go_chart.TextVerticalAlignUnset
DefaultGojaInterfaces["gochart"]["TextVerticalAlignBaseline"] = github_com_wcharczuk_go_chart.TextVerticalAlignBaseline
DefaultGojaInterfaces["gochart"]["TextVerticalAlignBottom"] = github_com_wcharczuk_go_chart.TextVerticalAlignBottom
DefaultGojaInterfaces["gochart"]["TextVerticalAlignMiddle"] = github_com_wcharczuk_go_chart.TextVerticalAlignMiddle
DefaultGojaInterfaces["gochart"]["TextVerticalAlignMiddleBaseline"] = github_com_wcharczuk_go_chart.TextVerticalAlignMiddleBaseline
DefaultGojaInterfaces["gochart"]["TextVerticalAlignTop"] = github_com_wcharczuk_go_chart.TextVerticalAlignTop
DefaultGojaInterfaces["gochart"]["TextWrapUnset"] = github_com_wcharczuk_go_chart.TextWrapUnset
DefaultGojaInterfaces["gochart"]["TextWrapNone"] = github_com_wcharczuk_go_chart.TextWrapNone
DefaultGojaInterfaces["gochart"]["TextWrapWord"] = github_com_wcharczuk_go_chart.TextWrapWord
DefaultGojaInterfaces["gochart"]["TextWrapRune"] = github_com_wcharczuk_go_chart.TextWrapRune
DefaultGojaInterfaces["gochart"]["Tick"] = github_com_wcharczuk_go_chart.Tick{}
DefaultGojaInterfaces["gochart"]["GenerateContinuousTicks"] = github_com_wcharczuk_go_chart.GenerateContinuousTicks
DefaultGojaInterfaces["gochart"]["TickPositionUnset"] = github_com_wcharczuk_go_chart.TickPositionUnset
DefaultGojaInterfaces["gochart"]["TickPositionBetweenTicks"] = github_com_wcharczuk_go_chart.TickPositionBetweenTicks
DefaultGojaInterfaces["gochart"]["TickPositionUnderTick"] = github_com_wcharczuk_go_chart.TickPositionUnderTick
DefaultGojaInterfaces["gochart"]["TimeSeries"] = github_com_wcharczuk_go_chart.TimeSeries{}
DefaultGojaInterfaces["gochart"]["Value"] = github_com_wcharczuk_go_chart.Value{}
DefaultGojaInterfaces["gochart"]["Value2"] = github_com_wcharczuk_go_chart.Value2{}
DefaultGojaInterfaces["gochart"]["TimeValueFormatterWithFormat"] = github_com_wcharczuk_go_chart.TimeValueFormatterWithFormat
DefaultGojaInterfaces["gochart"]["XAxis"] = github_com_wcharczuk_go_chart.XAxis{}
DefaultGojaInterfaces["gochart"]["YAxis"] = github_com_wcharczuk_go_chart.YAxis{}
DefaultGojaInterfaces["gochart"]["YAxisPrimary"] = github_com_wcharczuk_go_chart.YAxisPrimary
DefaultGojaInterfaces["gochart"]["YAxisSecondary"] = github_com_wcharczuk_go_chart.YAxisSecondary
DefaultGojaInterfaces["gochart"]["FloatValueFormatter"] = github_com_wcharczuk_go_chart.FloatValueFormatter
DefaultGojaInterfaces["gochart"]["FloatValueFormatterWithFormat"] = github_com_wcharczuk_go_chart.FloatValueFormatterWithFormat
DefaultGojaInterfaces["gochart"]["GetAlternateColor"] = github_com_wcharczuk_go_chart.GetAlternateColor
DefaultGojaInterfaces["gochart"]["GetDefaultColor"] = github_com_wcharczuk_go_chart.GetDefaultColor
DefaultGojaInterfaces["gochart"]["GetDefaultFont"] = github_com_wcharczuk_go_chart.GetDefaultFont
DefaultGojaInterfaces["gochart"]["Jet"] = github_com_wcharczuk_go_chart.Jet
DefaultGojaInterfaces["gochart"]["PercentValueFormatter"] = github_com_wcharczuk_go_chart.PercentValueFormatter
DefaultGojaInterfaces["gochart"]["TimeDateValueFormatter"] = github_com_wcharczuk_go_chart.TimeDateValueFormatter
DefaultGojaInterfaces["gochart"]["TimeHourValueFormatter"] = github_com_wcharczuk_go_chart.TimeHourValueFormatter
DefaultGojaInterfaces["gochart"]["TimeMinuteValueFormatter"] = github_com_wcharczuk_go_chart.TimeMinuteValueFormatter
DefaultGojaInterfaces["gochart"]["TimeValueFormatter"] = github_com_wcharczuk_go_chart.TimeValueFormatter
DefaultGojaInterfaces["gochart"]["Viridis"] = github_com_wcharczuk_go_chart.Viridis
DefaultGojaInterfaces["gochart"]["LastValueAnnotation"] = github_com_wcharczuk_go_chart.LastValueAnnotation
DefaultGojaInterfaces["gochart"]["NewBox"] = github_com_wcharczuk_go_chart.NewBox
DefaultGojaInterfaces["gochart"]["GenerateGridLines"] = github_com_wcharczuk_go_chart.GenerateGridLines
DefaultGojaInterfaces["gochart"]["Legend"] = github_com_wcharczuk_go_chart.Legend
DefaultGojaInterfaces["gochart"]["LegendLeft"] = github_com_wcharczuk_go_chart.LegendLeft
DefaultGojaInterfaces["gochart"]["LegendThin"] = github_com_wcharczuk_go_chart.LegendThin
DefaultGojaInterfaces["gochart"]["PNG"] = github_com_wcharczuk_go_chart.PNG
DefaultGojaInterfaces["gochart"]["SVG"] = github_com_wcharczuk_go_chart.SVG
DefaultGojaInterfaces["gochart"]["StyleShow"] = github_com_wcharczuk_go_chart.StyleShow
DefaultGojaInterfaces["gochart"]["StyleTextDefaults"] = github_com_wcharczuk_go_chart.StyleTextDefaults
DefaultGojaInterfaces["gochart"]["GenerateContinuousTicks"] = github_com_wcharczuk_go_chart.GenerateContinuousTicks
DefaultGojaInterfaces["gochart"]["TimeValueFormatterWithFormat"] = github_com_wcharczuk_go_chart.TimeValueFormatterWithFormat

			 			}	
			 		}
			 	}
			 }
		}
	}
}